In [31]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
%matplotlib inline

In [32]:
from sklearn import decomposition
from sklearn.decomposition import PCA
from sklearn.decomposition import PCA, TruncatedSVD

In [88]:
g_trend = pd.read_csv("Google_Trends.csv")
g_trend.head()

Week  a.influenza  acute.bronchitis  body.temperature  \
0  1/10/2004           11                50                58   
1  1/17/2004            7                41                70   
2  1/24/2004            6                40                53   
3  1/31/2004            4                32                57   
4   2/7/2004            3                31                46   

   braun.thermoscan  break.a.fever  bronchitis  chest.cold  cold.and.flu  \
0               100             15          34          27            26   
1                54             12          31          17            20   
2                40             15          29          20            16   
3                26             18          25          21            12   
4                80             21          25           9            10   

   cold.or.flu  ...  treating.flu  treating.the.flu  treatment.for.flu  \
0           39  ...            32                78                  7   
1           11  ...            26                41                  9   
2            8  ...            29                41                  6   
3           13  ...            33                41                  5   
4           15  ...            33                42                  5   

   treatment.for.the.flu  tussin  tussionex  type.a.influenza  \
0                     42      64         79                20   
1                      0      20         58                16   
2                      0      44         52                16   
3                      0      52         42                16   
4                      0      34         51                18   

   upper.respiratory  walking.pneumonia  what.to.do.if.you.have.the.flu  
0                 37                 57                               0  
1                 21                 42                               0  
2                 17                 38                               0  
3                 24                 45                               0  
4                 25                 26                               0  

[5 rows x 130 columns]

In [59]:
g_trend.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 653 entries, 0 to 652
Columns: 130 entries, Week to what.to.do.if.you.have.the.flu
dtypes: int64(129), object(1)
memory usage: 663.3+ KB


In [45]:
#for col in g_trend.columns: 
    #print(col) 

In [73]:
X = g_trend.drop('Week',1)
y = g_trend['Week']

In [74]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [75]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train_scaled = sc.fit_transform(X_train)
X_test_scaled = sc.transform(X_test)

In [79]:
from sklearn.decomposition import PCA

pca = PCA(.95)
X_train_pca = pca.fit_transform(X_train_scaled)
X_test_pca = pca.transform(X_test_scaled)

In [80]:
explained_variance = pca.explained_variance_ratio_
print(explained_variance)

[0.61040025 0.13829097 0.04981203 0.02697771 0.02610939 0.01303062
 0.01263289 0.00763148 0.00704983 0.00649585 0.0053944  0.00497284
 0.00462699 0.00455577 0.00376045 0.00338432 0.00328231 0.00307831
 0.00283623 0.00280276 0.00271187 0.00246263 0.00235385 0.00226108
 0.00220398 0.00207324]


In [81]:
len(explained_variance)

26

In [62]:
#sorted(zip(explained_variance, g_trend.columns), reverse=True)

In [84]:
from sklearn.decomposition import PCA

pca = PCA(n_components=2)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)


In [85]:
from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(max_depth=2, random_state=0)
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

C:\Users\ihuang\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [86]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

cm = confusion_matrix(y_test, y_pred)
print(cm)
print('Accuracy ' + str(accuracy_score(y_test, y_pred)))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Accuracy 0.0
